id: I8961718B
initial_creation_type: ebook
source_metadata:
  id: RDI-SS-42-2
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  author: མཛད་པ་པོ། རྫ་དཔལ་སྤྲུལ་རིན་པོ་ཆེ།
  authors: &id001
  - མཛད་པ་པོ། རྫ་དཔལ་སྤྲུལ་རིན་པོ་ཆེ།
  sku: RDI-SS-42-2
  cover: Book-42_Cover_Part-2_Front.jpg
  volume: {}
ebook_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors: *id001
  sku: RDI-SS-42-2
  cover: Book-42_Cover_Part-2_Front.jpg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
- Tsawa
- Yigchung
